# -*- coding: utf-8 -*-
"""Broadstreet_API_Example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ioHdlDIpCHkrM5W_gXbBBPObp2H7x2W
"""

# Import required Modules 

import requests
import json
import matplotlib.pyplot as plt
import datetime 
import pprint

# Get State Data fro July 23 - 25 2020 for NC and AK

stateList = ["NC", 'AK']
start = "2020-07-23"
end = "2020-07-25"
fips = ["05000US37189", "05000US02060", "05000US37085", "05000US37105", "05000US02110"]

#create a set of nested dictionaries, containing keys 'query' and 'variables' 
query = {'query':"""query CovidQuery($input: Covid19SearchInput!)
    {covid19Daily(search: $input){
        edges{
          node{
            fips
            county
            state
            day
            tstpos
            mort
          }
        }
      }
      }""",'variables': {"input": {"startDay": start, "endDay": end,"stateList":stateList, "fipsList":fips}}}

url = "https://demo.broadstreet.io/graphql"

# Print out the response

r = requests.get(url, json=query,
    headers={'authorization': 'AIzaSyCbMEN223iJ2r-GhBcPHda0V7mo3vz1uRo'},)

print(json.dumps(r.json(), indent=4))

# Store the data in an easily accessible fomat

data = r.json()['data']['covid19Daily']['edges']
print(json.dumps(data, indent=4))

# Optional: Create a dictonary of data 

casesData = dict()
for i in data:
    x = i['node']
    if x['county'] in casesData:
      casesData[x['county']]['cases'].append(x['tstpos'])
      casesData[x['county']]['dates'].append(datetime.datetime.strptime(x['day'],"%Y-%m-%d").date())
    else:
      casesData[x['county']] = {'cases':[x['tstpos']], 'dates': [datetime.datetime.strptime(x['day'],"%Y-%m-%d").date()]}
  
print(casesData)

# Visualize the Data

fig1 = plt.plot(casesData['Juneau City and Borough, Alaska']['dates'], casesData['Juneau City and Borough, Alaska']['cases'])
fig1 = plt.plot(casesData['Watauga County, North Carolina']['dates'], casesData['Watauga County, North Carolina']['cases'])

fig2 = plt.plot(casesData['Watauga County, North Carolina']['dates'], casesData['Watauga County, North Carolina']['cases'])